# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from a_star_algorithm/AlgorithmMessage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import a_star_algorithm.msg

class AlgorithmMessage(genpy.Message):
  _md5sum = "63a360c1d5e98eca0dd6fb4c67c4258a"
  _type = "a_star_algorithm/AlgorithmMessage"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PlatformMessage platform
PathMessage activePath
PathMessage[] paths
================================================================================
MSG: a_star_algorithm/PlatformMessage
int32 id
int32 size
VectorMessage start
VectorMessage end
int32[] data

================================================================================
MSG: a_star_algorithm/VectorMessage
int32 x
int32 y
================================================================================
MSG: a_star_algorithm/PathMessage
int32 id
int32 sizeOfNodes
NodeMessage[] nodes
================================================================================
MSG: a_star_algorithm/NodeMessage
VectorMessage location
int32 value"""
  __slots__ = ['platform','activePath','paths']
  _slot_types = ['a_star_algorithm/PlatformMessage','a_star_algorithm/PathMessage','a_star_algorithm/PathMessage[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       platform,activePath,paths

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AlgorithmMessage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.platform is None:
        self.platform = a_star_algorithm.msg.PlatformMessage()
      if self.activePath is None:
        self.activePath = a_star_algorithm.msg.PathMessage()
      if self.paths is None:
        self.paths = []
    else:
      self.platform = a_star_algorithm.msg.PlatformMessage()
      self.activePath = a_star_algorithm.msg.PathMessage()
      self.paths = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.platform.id, _x.platform.size, _x.platform.start.x, _x.platform.start.y, _x.platform.end.x, _x.platform.end.y))
      length = len(self.platform.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.platform.data))
      _x = self
      buff.write(_get_struct_2i().pack(_x.activePath.id, _x.activePath.sizeOfNodes))
      length = len(self.activePath.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.activePath.nodes:
        _v1 = val1.location
        _x = _v1
        buff.write(_get_struct_2i().pack(_x.x, _x.y))
        _x = val1.value
        buff.write(_get_struct_i().pack(_x))
      length = len(self.paths)
      buff.write(_struct_I.pack(length))
      for val1 in self.paths:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.id, _x.sizeOfNodes))
        length = len(val1.nodes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.nodes:
          _v2 = val2.location
          _x = _v2
          buff.write(_get_struct_2i().pack(_x.x, _x.y))
          _x = val2.value
          buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.platform is None:
        self.platform = a_star_algorithm.msg.PlatformMessage()
      if self.activePath is None:
        self.activePath = a_star_algorithm.msg.PathMessage()
      if self.paths is None:
        self.paths = None
      end = 0
      _x = self
      start = end
      end += 24
      (_x.platform.id, _x.platform.size, _x.platform.start.x, _x.platform.start.y, _x.platform.end.x, _x.platform.end.y,) = _get_struct_6i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.platform.data = s.unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.activePath.id, _x.activePath.sizeOfNodes,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.activePath.nodes = []
      for i in range(0, length):
        val1 = a_star_algorithm.msg.NodeMessage()
        _v3 = val1.location
        _x = _v3
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (val1.value,) = _get_struct_i().unpack(str[start:end])
        self.activePath.nodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.paths = []
      for i in range(0, length):
        val1 = a_star_algorithm.msg.PathMessage()
        _x = val1
        start = end
        end += 8
        (_x.id, _x.sizeOfNodes,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.nodes = []
        for i in range(0, length):
          val2 = a_star_algorithm.msg.NodeMessage()
          _v4 = val2.location
          _x = _v4
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
          start = end
          end += 4
          (val2.value,) = _get_struct_i().unpack(str[start:end])
          val1.nodes.append(val2)
        self.paths.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.platform.id, _x.platform.size, _x.platform.start.x, _x.platform.start.y, _x.platform.end.x, _x.platform.end.y))
      length = len(self.platform.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.platform.data.tostring())
      _x = self
      buff.write(_get_struct_2i().pack(_x.activePath.id, _x.activePath.sizeOfNodes))
      length = len(self.activePath.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.activePath.nodes:
        _v5 = val1.location
        _x = _v5
        buff.write(_get_struct_2i().pack(_x.x, _x.y))
        _x = val1.value
        buff.write(_get_struct_i().pack(_x))
      length = len(self.paths)
      buff.write(_struct_I.pack(length))
      for val1 in self.paths:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.id, _x.sizeOfNodes))
        length = len(val1.nodes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.nodes:
          _v6 = val2.location
          _x = _v6
          buff.write(_get_struct_2i().pack(_x.x, _x.y))
          _x = val2.value
          buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.platform is None:
        self.platform = a_star_algorithm.msg.PlatformMessage()
      if self.activePath is None:
        self.activePath = a_star_algorithm.msg.PathMessage()
      if self.paths is None:
        self.paths = None
      end = 0
      _x = self
      start = end
      end += 24
      (_x.platform.id, _x.platform.size, _x.platform.start.x, _x.platform.start.y, _x.platform.end.x, _x.platform.end.y,) = _get_struct_6i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.platform.data = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      _x = self
      start = end
      end += 8
      (_x.activePath.id, _x.activePath.sizeOfNodes,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.activePath.nodes = []
      for i in range(0, length):
        val1 = a_star_algorithm.msg.NodeMessage()
        _v7 = val1.location
        _x = _v7
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (val1.value,) = _get_struct_i().unpack(str[start:end])
        self.activePath.nodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.paths = []
      for i in range(0, length):
        val1 = a_star_algorithm.msg.PathMessage()
        _x = val1
        start = end
        end += 8
        (_x.id, _x.sizeOfNodes,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.nodes = []
        for i in range(0, length):
          val2 = a_star_algorithm.msg.NodeMessage()
          _v8 = val2.location
          _x = _v8
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2i().unpack(str[start:end])
          start = end
          end += 4
          (val2.value,) = _get_struct_i().unpack(str[start:end])
          val1.nodes.append(val2)
        self.paths.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_6i = None
def _get_struct_6i():
    global _struct_6i
    if _struct_6i is None:
        _struct_6i = struct.Struct("<6i")
    return _struct_6i
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
