# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from a_star_algorithm/NodeMessage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import a_star_algorithm.msg

class NodeMessage(genpy.Message):
  _md5sum = "055d2c8f3fa27ed8eee4293f534be47c"
  _type = "a_star_algorithm/NodeMessage"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """VectorMessage location
int32 g
================================================================================
MSG: a_star_algorithm/VectorMessage
int32 x
int32 y"""
  __slots__ = ['location','g']
  _slot_types = ['a_star_algorithm/VectorMessage','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       location,g

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NodeMessage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.location is None:
        self.location = a_star_algorithm.msg.VectorMessage()
      if self.g is None:
        self.g = 0
    else:
      self.location = a_star_algorithm.msg.VectorMessage()
      self.g = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3i().pack(_x.location.x, _x.location.y, _x.g))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.location is None:
        self.location = a_star_algorithm.msg.VectorMessage()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.location.x, _x.location.y, _x.g,) = _get_struct_3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3i().pack(_x.location.x, _x.location.y, _x.g))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.location is None:
        self.location = a_star_algorithm.msg.VectorMessage()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.location.x, _x.location.y, _x.g,) = _get_struct_3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3i = None
def _get_struct_3i():
    global _struct_3i
    if _struct_3i is None:
        _struct_3i = struct.Struct("<3i")
    return _struct_3i
