// Generated by gencpp from file a_star_algorithm/NodeMessage.msg
// DO NOT EDIT!


#ifndef A_STAR_ALGORITHM_MESSAGE_NODEMESSAGE_H
#define A_STAR_ALGORITHM_MESSAGE_NODEMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <a_star_algorithm/VectorMessage.h>

namespace a_star_algorithm
{
template <class ContainerAllocator>
struct NodeMessage_
{
  typedef NodeMessage_<ContainerAllocator> Type;

  NodeMessage_()
    : location()
    , value(0)  {
    }
  NodeMessage_(const ContainerAllocator& _alloc)
    : location(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef  ::a_star_algorithm::VectorMessage_<ContainerAllocator>  _location_type;
  _location_type location;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::a_star_algorithm::NodeMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a_star_algorithm::NodeMessage_<ContainerAllocator> const> ConstPtr;

}; // struct NodeMessage_

typedef ::a_star_algorithm::NodeMessage_<std::allocator<void> > NodeMessage;

typedef boost::shared_ptr< ::a_star_algorithm::NodeMessage > NodeMessagePtr;
typedef boost::shared_ptr< ::a_star_algorithm::NodeMessage const> NodeMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a_star_algorithm::NodeMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::a_star_algorithm::NodeMessage_<ContainerAllocator1> & lhs, const ::a_star_algorithm::NodeMessage_<ContainerAllocator2> & rhs)
{
  return lhs.location == rhs.location &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::a_star_algorithm::NodeMessage_<ContainerAllocator1> & lhs, const ::a_star_algorithm::NodeMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace a_star_algorithm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a_star_algorithm::NodeMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a_star_algorithm::NodeMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_star_algorithm::NodeMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdea65e7844ffe19096249ab018e2217";
  }

  static const char* value(const ::a_star_algorithm::NodeMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdea65e7844ffe19ULL;
  static const uint64_t static_value2 = 0x096249ab018e2217ULL;
};

template<class ContainerAllocator>
struct DataType< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a_star_algorithm/NodeMessage";
  }

  static const char* value(const ::a_star_algorithm::NodeMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "VectorMessage location\n"
"int32 value\n"
"================================================================================\n"
"MSG: a_star_algorithm/VectorMessage\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::a_star_algorithm::NodeMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a_star_algorithm::NodeMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a_star_algorithm::NodeMessage_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    s << std::endl;
    Printer< ::a_star_algorithm::VectorMessage_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // A_STAR_ALGORITHM_MESSAGE_NODEMESSAGE_H
