// Generated by gencpp from file a_star_algorithm/pathMessage.msg
// DO NOT EDIT!


#ifndef A_STAR_ALGORITHM_MESSAGE_PATHMESSAGE_H
#define A_STAR_ALGORITHM_MESSAGE_PATHMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace a_star_algorithm
{
template <class ContainerAllocator>
struct pathMessage_
{
  typedef pathMessage_<ContainerAllocator> Type;

  pathMessage_()
    : id(0)
    , sizeOfPath(0)
    , path()  {
    }
  pathMessage_(const ContainerAllocator& _alloc)
    : id(0)
    , sizeOfPath(0)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int8_t _sizeOfPath_type;
  _sizeOfPath_type sizeOfPath;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::a_star_algorithm::pathMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a_star_algorithm::pathMessage_<ContainerAllocator> const> ConstPtr;

}; // struct pathMessage_

typedef ::a_star_algorithm::pathMessage_<std::allocator<void> > pathMessage;

typedef boost::shared_ptr< ::a_star_algorithm::pathMessage > pathMessagePtr;
typedef boost::shared_ptr< ::a_star_algorithm::pathMessage const> pathMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a_star_algorithm::pathMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a_star_algorithm::pathMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::a_star_algorithm::pathMessage_<ContainerAllocator1> & lhs, const ::a_star_algorithm::pathMessage_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.sizeOfPath == rhs.sizeOfPath &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::a_star_algorithm::pathMessage_<ContainerAllocator1> & lhs, const ::a_star_algorithm::pathMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace a_star_algorithm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::a_star_algorithm::pathMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a_star_algorithm::pathMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a_star_algorithm::pathMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a_star_algorithm::pathMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_star_algorithm::pathMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_star_algorithm::pathMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a_star_algorithm::pathMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d11fa3ccd9cda428b05f117412d7ba8b";
  }

  static const char* value(const ::a_star_algorithm::pathMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd11fa3ccd9cda428ULL;
  static const uint64_t static_value2 = 0xb05f117412d7ba8bULL;
};

template<class ContainerAllocator>
struct DataType< ::a_star_algorithm::pathMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a_star_algorithm/pathMessage";
  }

  static const char* value(const ::a_star_algorithm::pathMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a_star_algorithm::pathMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"int8 sizeOfPath\n"
"int8[] path\n"
;
  }

  static const char* value(const ::a_star_algorithm::pathMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a_star_algorithm::pathMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.sizeOfPath);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pathMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a_star_algorithm::pathMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a_star_algorithm::pathMessage_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "sizeOfPath: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sizeOfPath);
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // A_STAR_ALGORITHM_MESSAGE_PATHMESSAGE_H
